apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-serivce
    app: demo-voting-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30004
  selector:
    name: demo-voting-pod
    app: voting-app-pod